'use strict';
const { test, before, after } = require('node:test'); const assert=require('node:assert'); const {spawn}=require('child_process'); const fs=require('fs'); const os=require('os'); const path=require('path');
const PORT=4300+Math.floor(Math.random()*100), BASE=`http://127.0.0.1:${PORT}`, DATA_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'jwre-auth-')); let child;
function client(jar={}){return async(url,o={})=>{const r=await fetch(BASE+url,{redirect:'manual',...o,headers:{...(o.headers||{}),cookie:Object.entries(jar).map(([k,v])=>`${k}=${v}`).join('; ')}});for(const sc of r.headers.getSetCookie?.()||[]){const q=sc.split(';')[0],i=q.indexOf('=');jar[q.slice(0,i)]=q.slice(i+1)}return r}}
const form=x=>({method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(x)});
before(()=>new Promise((ok,no)=>{child=spawn(process.execPath,['src/server.js'],{cwd:path.join(__dirname,'..'),env:{...process.env,PORT:String(PORT),DATA_DIR,ADMIN_PASSWORD:'owner-pass-123',SESSION_SECRET:'auth-test-secret',STUDIO_OWNER_EMAIL:'owner@example.com',DEMO_AGENT_PASSWORD:'agent-pass-123'}});child.stdout.on('data',d=>String(d).includes('listening')&&ok());child.stderr.on('data',d=>process.stderr.write(d));setTimeout(()=>no(new Error('timeout')),10000)}));
after(()=>{child.kill('SIGKILL');fs.rmSync(DATA_DIR,{recursive:true,force:true})});
test('legacy owner bootstraps once, photographer is blocked from team',async()=>{const owner=client();let r=await owner('/admin/login',form({email:'owner@example.com',password:'owner-pass-123'}));assert.equal(r.status,303);r=await owner('/admin/team');assert.equal(r.status,200);const html=await r.text();assert.match(html,/Studio team/);r=await owner('/admin/team',form({name:'Pat Photo',email:'pat@example.com',role:'photographer'}));assert.equal(r.status,200);const body=await r.text(), pw=body.match(/<code class="cred">([^<]+)/)[1];const p=client();r=await p('/admin/login',form({email:'pat@example.com',password:pw}));assert.equal(r.status,303);assert.equal(r.headers.get('location'),'/admin/password');});
test('recovery response does not enumerate users and does not mint tokens without delivery',async()=>{for(const email of ['owner@example.com','nobody@example.com']){const r=await fetch(BASE+'/admin/recover',form({email}));assert.equal(r.status,200);assert.match(await r.text(),/If an account matches/)}const db=JSON.parse(fs.readFileSync(path.join(DATA_DIR,'db.json'),'utf8'));assert.equal((db.account_recovery_tokens||[]).length,0);});
test('owner catalog changes reach services and booking while inactive items disappear',async()=>{const owner=client();let r=await owner('/admin/login',form({email:'owner@example.com',password:'owner-pass-123'}));assert.equal(r.status,303);r=await owner('/admin/catalog',form({id:'social-starter',kind:'package',name:'Social Starter',tagline:'Photos for social launch',price:'99.00',includes:'10 edited photos\nVertical cover image',sort_order:'5',active:'1'}));assert.equal(r.status,303);let html=await (await fetch(BASE+'/services')).text();assert.match(html,/Social Starter/);const agent=client();await agent('/portal/login',form({email:'dana.rivera@example.com',password:'agent-pass-123'}));html=await (await agent('/book')).text();assert.match(html,/Social Starter/);r=await owner('/admin/catalog/social-starter',form({id:'social-starter',kind:'package',name:'Social Starter',tagline:'Photos for social launch',price:'109.00',includes:'10 edited photos',sort_order:'5'}));assert.equal(r.status,303);html=await (await fetch(BASE+'/services')).text();assert.doesNotMatch(html,/Social Starter/);});
